# =================================
# SERVICE CONFIGURATION
# =================================
spring:
  application:
    name: gescom-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lorince-tawamba/gescom-centralize-config.git
          default-label: main
          username: lorince-tawamba
          password: votre-mot-de-passe-ici
          search-paths: gescom-eureka-discovery-service, gescom-gateway-service, gescom-gestion-client, gescom-gestion-produit, gescom-gestion-commande, gescom-gestion-facture, gescom-gestion-livraison

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
server:
  port: 8888
